# Generated by Django 3.2.6 on 2021-08-25 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='textbook_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.ratingstar', verbose_name='Звезда'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='assignments',
            field=models.ManyToManyField(related_name='quiz_assignments', to='dictionary.Assignment', verbose_name='Предложения на перевод'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grammar',
            field=models.ManyToManyField(related_name='lesson_grammar', to='dictionary.GrammarTopic', verbose_name='грамматические темы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='dictionary.textbook', verbose_name='Учебник'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='hsk',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='hsk_level', to='dictionary.hsk'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='hsk',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='hsk_grammar_level', to='dictionary.hsk'),
        ),
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.ManyToManyField(related_name='course_assignment', to='dictionary.Assignment', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ManyToManyField(related_name='course_mentor', to=settings.AUTH_USER_MODEL, verbose_name='Ментор'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='course_student', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.comment', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='grammar',
            field=models.ManyToManyField(blank=True, related_name='assignment_grammar', to='dictionary.GrammarTopic', verbose_name='Грамматика'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='assignment_keywords', to='dictionary.Keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lessons',
            field=models.ManyToManyField(related_name='assignment_lesson', to='dictionary.Lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='article_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='grammar',
            field=models.ManyToManyField(blank=True, related_name='article_grammar', to='dictionary.GrammarTopic', verbose_name='Грамматика'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='article_keywords', to='dictionary.Keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='article_lesson', to='dictionary.Lesson', verbose_name='Уроки'),
        ),
    ]
